# Generated by Django 5.2 on 2025-05-14 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0003_district_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('response_time', models.FloatField()),
                ('active_users', models.IntegerField()),
                ('error_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='admindashbo_timesta_ddc277_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('notification_type', models.CharField(choices=[('system_alert', 'System Alert'), ('user_activity', 'User Activity'), ('performance_alert', 'Performance Alert'), ('security_alert', 'Security Alert'), ('info', 'Information')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='admindashbo_level_00f599_idx'), models.Index(fields=['notification_type'], name='admindashbo_notific_3a6e8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('view', 'Page View'), ('create', 'Resource Creation'), ('update', 'Resource Update'), ('delete', 'Resource Deletion'), ('download', 'File Download'), ('upload', 'File Upload'), ('api_call', 'API Call')], max_length=20)),
                ('resource', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action', 'timestamp'], name='admindashbo_user_id_6e9795_idx')],
            },
        ),
    ]
