# Generated by Django 5.2 on 2025-05-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0004_systemmetrics_adminnotification_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnotification',
            name='read_by',
        ),
        migrations.DeleteModel(
            name='SystemMetrics',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminNotification',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
