# Generated by Django 4.2.7 on 2023-11-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0009_auto_20231114_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Display this exam on the home page'),
        ),
    ] 