# Generated by Django 5.2 on 2025-05-20 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0010_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ad_code', models.TextField(help_text='Paste your third-party ad code here (e.g., Google AdSense)')),
                ('location', models.CharField(choices=[('above_content', 'Above Content'), ('below_content', 'Below Content'), ('sidebar_top', 'Sidebar Top'), ('sidebar_bottom', 'Sidebar Bottom'), ('between_content', 'Between Content')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.userprofile')),
            ],
            options={
                'verbose_name': 'Ad Setting',
                'verbose_name_plural': 'Ad Settings',
                'ordering': ['location', '-created_at'],
            },
        ),
    ]
