# Generated by Django 5.2.1 on 2025-05-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0011_adsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='module',
            new_name='subject',
        ),
    ]
