# Generated by Django 5.2 on 2025-06-03 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0010_exam_show_on_home'),
        ('admindashboard', '0012_rename_module_note_subject'),
    ]

    operations = [
    ]
