# Generated by Django 5.2 on 2025-06-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0013_merge_20250603_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
