# Generated by Django 5.2 on 2025-05-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicpage', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
